apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-springboot
spec:
  selector:
    matchLabels:
      app: k8s-springboot
  replicas: 1
  template:
    metadata:
      labels:
        app: k8s-springboot
    spec:
      containers:
        - name: k8s-springboot
          image: k8s-springboot:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          resources:
            requests:
              cpu: 200m
              memory: 1Gi
            limits:
              cpu: 1
              memory: 1Gi