apiVersion: apps/v1
kind: Deployment # Oluşturduğumuz Kubernetes kaynak türü
metadata:
  name: k8s-springboot
spec:
  selector:
    matchLabels:
      app: k8s-springboot
  replicas: 2 # Bu dağıtım için oluşturulacak kopyaların sayısı
  template:
    metadata:
      labels:
        app: k8s-springboot
    spec:
      containers:
        - name: k8s-springboot
          image: k8s-springboot # Docker build ederken oluşturduğumuz imaj ismi
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080