apiVersion: v1
kind: Service
metadata: # Oluşturduğumuz kaynak türünün meta verileri
  name: k8s-springboot-svc
spec:
  selector:
    app: k8s-springboot
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080 # Hizmetin açığa çıkardığı bağlantı noktası
  type: NodePort # hizmet türü